server.port=${PORT:10000}
## spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
## --- PostgreSQL for production (Render) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
logging.level.org.springframework.core.env=DEBUG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## --- H2 for local development (commented out) ---
# spring.datasource.url=jdbc:h2:file:./data/secure_cloud_storage_db;DB_CLOSE_DELAY=-1
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.jpa.show-sql=true

app.auth.secret=secure-cloud-storage-local-dev-secret
app.auth.ttl-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${spring.mail.username:}