
server.port=8080
# --- MongoDB Configuration ---
spring.data.mongodb.uri=mongodb://phishadmin:jaysalian123@cluster0-shard-00-00.vwwsm.mongodb.net:27017,cluster0-shard-00-01.vwwsm.mongodb.net:27017,cluster0-shard-00-02.vwwsm.mongodb.net:27017/securecloud?ssl=true&replicaSet=atlas-1ug55h-shard-0&authSource=admin&retryWrites=true&w=majority
spring.data.mongodb.database=securecloud

logging.level.org.springframework.core.env=DEBUG


app.auth.secret=secure-cloud-storage-local-dev-secret
app.auth.ttl-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${spring.mail.username:}